name: tests-auth

on:
  pull_request:
    paths:
      - 'server/**'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 
      - run: cd src && npm install && npm run test:ci
